[package]
name = "x39-lambda"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7"
serde = { version = "1.0.147", features = ["serde_derive"] }
tracing = "0"
tracing-test = "0.2.3"
uuid = { version = "1.2.1", features = ["serde", "v4"] }

[dev-dependencies]
tracing-test = "0"
